<a href="https://colab.research.google.com/github/Juosorioca420/DiscretasII/blob/main/Grupos_y_CuadrosLatinos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Asignación 01

Determinar si una tabla de Cayley representa un cuadro latino y/o un Grupo.

---
Es importante hacer la distinción este entre estos dos conceptos, pues todo Grupo, bajo su representación de cuadro Cayley en un cuadro latino, pero no todo cuadro latino es Grupo.

Bajo esta aclaración, se presenta la necesidad de identificar cuando (G, $\cdot$), con G un conjunto y $\cdot$ una operacion binaria, es un grupo. Dada las propiedades que estas estructuras algebraicas garantizan, es posible estudiar una rica variedad de fenomenos, como las organizaciones sociales o moleculares, los grafos en matematicas entre muchos más problemas que por su complejidad resulta necesario abstraerlos en estructuras que se puedan estudiar bajo propiedades y teoremas generales y descomponer en subestructuras computacionalmente más economicas y sencillas de entender; estructuras como lo son los Grupos.

In [7]:
import numpy as np

Primeramente se etermina si un arreglo es cuadro latino.

> Vemos que no haya duplicados dentro de los *n* elementos de las filas y que todos los elementos de las filas esten contenidos en un mismo grupo $C$.


\begin{align*}
(m, C) \longrightarrow bool
\end{align*}

* m : matriz de Cayley
* C : Conjunto 

In [68]:
def latino( m, C ):
  n = len(m) # matriz nxn

  for fil in m:
    dup = set(fil) #elimina duplicados
    if len(dup) < n :
      return False
    
    for elem in fil:
      if elem not in C:
        return False

  return True

Luego se determina si un arreglo es grupo.


> Se debe saber si la operacion en cerrada, asociativa, hay neutro e inverso.

> Cada requerimiento sera una funcion auxiliar de grupo, que finalmente solo
  evaluara que se cumpla cada una de estas. 

\begin{align*}
(m, C) \longrightarrow bool
\end{align*}

* m : matriz de Cayley
* C : Conjunto 

In [60]:
def grupo( m, C ):

  def cerrada(m): #Veamos que cada elemento de m pertenezca a C, el conjunto originario
    for fil in m:
      for elem in fil:
        if elem not in C:
          return False
    return True

  def neutro(m, C): #El elemento neutro genera una fila y columna iguales a C en la posición i.
    n = len(m)
    t = m.transpose()
    e = [] #lista para almacenar el elemento neutro

    for i in range(n):
      fil, col = m[i], t[i]
      if ( np.array_equal( fil, C ) ) and ( np.array_equal( col, C ) ):
        e.append( C[i] )

    if len(e) == 1: #Asegurar que e sea unico
      print( f'Elemento Neutro: { e[0] }\n' )
      return True, e[0]
    else:
      return False, None

  def inverso(m, C, e):
    #Debe existir una aparicion unica de e en cada fila y columna, así unicamente el elemento i (fila) es inverso de j (columna) y viceversa.
    n = len(m); t = m.transpose()
    for i in range(n):
      fil = [ x for x in m[i] if x == e ]
      col = [ x for x in t[i] if x == e ]

      if ( len(fil) + len(col) != 2 ):
        return False

    return True

  def asociativa( m, C ): #Se analiza la igualdad de las posibles operaciones en un loop triple [O(n^3)]
    n = len(m)
    for i in range(n-2):
     for j in range(i+1, n-1):
        for k in range(j+1, n):  #Todas las posibles permutaciones de indices
          parentesis = np.where( C == m[j][k] )[0][0]
          izquierda = m[i][parentesis] # i * (j*k)

          parentesis = np.where( C == m[i][j] )[0][0]
          derecha = m[parentesis][k] # (i*j) * k

          if izquierda != derecha:
            return False
    return True

  if cerrada(m):
    flag, e = neutro(m, C)
    if flag:
      if inverso(m, C, e):
        if asociativa(m, C):
          return True 
          #Los if anidados ahorran un poco de tiempo al programa.
          #En caso que una condicion falte, inmediatamente ya no es Grupo.
  return False

Por ultimo se integran las funciones en un unico metodo, asegurandose de correr primero la funcion de $\verb|grupo()|$, pues en caso de ser verdadera, podemos decir que la tabla tambien es cuadro latino.

In [66]:
def main(m , C):
  g = grupo(m, C)
  if g:
    return print(f'La tabla representa un Grupo y es Cuadro latino.')
  else:
    l = latino(m, C)
    if l:
      return print(f'La tabla no es un Grupo y es Cuadro latino.')
    else:
      return print(f'No es Grupo ni Cuadro latino.')

El codigo se pone a prueba con el Grupo trabajado en clase:

In [70]:
C = np.array(['g1','g2','g3','g4','g5','g6','g7','g8'])
m = np.array([
                 ['g1','g2','g3','g4','g5','g6','g7','g8'],
                ['g2','g3','g4','g1','g7','g8','g6','g5'],
                ['g3','g4','g1','g2','g6','g5','g8','g7'],
               ['g4','g1','g2','g3','g8','g7','g5','g6'],
              ['g5','g8','g6','g7','g1','g3','g4','g2'],
               ['g6','g7','g5','g8','g3','g1','g2','g4'],
              ['g7','g5','g8','g6','g2','g4','g1','g3'],
              ['g8','g6','g7','g5','g4','g2','g3','g1']
                ]) #Tabla puesta a prueba en clase.
print(m)

main(m, C)

[['g1' 'g2' 'g3' 'g4' 'g5' 'g6' 'g7' 'g8']
 ['g2' 'g3' 'g4' 'g1' 'g7' 'g8' 'g6' 'g5']
 ['g3' 'g4' 'g1' 'g2' 'g6' 'g5' 'g8' 'g7']
 ['g4' 'g1' 'g2' 'g3' 'g8' 'g7' 'g5' 'g6']
 ['g5' 'g8' 'g6' 'g7' 'g1' 'g3' 'g4' 'g2']
 ['g6' 'g7' 'g5' 'g8' 'g3' 'g1' 'g2' 'g4']
 ['g7' 'g5' 'g8' 'g6' 'g2' 'g4' 'g1' 'g3']
 ['g8' 'g6' 'g7' 'g5' 'g4' 'g2' 'g3' 'g1']]
Elemento Neutro: g1

La tabla representa un Grupo y es Cuadro latino.



---
---
Pruebas


In [22]:
a = np.array([0, 2, 3, 3, 5, 9, 16, 17, 9])
b = np.array([0, 2, 3, 3, 5, 9, 16, 9, 17])

print(a == b, np.array_equal(a,b))

[ True  True  True  True  True  True  True False False] False


In [54]:
a = np.matrix([[9, 3, 9], [9, 10, 11], [11, 17, 11]])
b = a.transpose()

print(a)
print()
print(b)

a = np.array([0, 2, 3, 3, 5, 9, 16, 17, 9])
c = a[ a == 2 ]; d = a[ np.where( a <= 5 ) ]; e = np.where( a == 5 ); f = a[4]
print(c, d, e[0], f) # where me devuelve el indice en una tupla de 2 elementos

[[ 9  3  9]
 [ 9 10 11]
 [11 17 11]]

[[ 9  9 11]
 [ 3 10 17]
 [ 9 11 11]]
[2] [0 2 3 3 5] [4] 5
